apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: devjeans-frontend-hpa
  namespace: devjeans
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devjeans-front
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
