name: Front CI
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Python
        run: |
          sudo apt-get update
          sudo apt-get install python3
          
      - name: Set Python PATH
        run: echo "export PATH=/usr/bin/python3:\$PATH" >> $GITHUB_ENV
        
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: 도커 이미지 빌드 # (2)
        run: docker build -t patnmat/devjeans-front .

      - name: Docker Hub 로그인 # (3)
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Hub 퍼블리시 # (4)
        run: docker push patnmat/devjeans-front
