name: Front CI
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 저장소 Checkout
        uses: actions/checkout@v3

      - name: 도커 이미지 빌드 # (2)
        id: docker_build
        run: |
          DOCKER_TAG=v${{ github.run_number }}
          docker build -t patnmat/devjeans-front:${DOCKER_TAG} .
          echo "DOCKER_TAG=${DOCKER_TAG}" >> $GITHUB_ENV

      - name: Docker Hub 로그인 # (3)
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Hub 퍼블리시 # (4)
        run: |
          DOCKER_TAG=${{ env.DOCKER_TAG }}
          docker push patnmat/devjeans-front:${DOCKER_TAG}
